//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppPageTitle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppPageTitle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Resources.AppPageTitle", typeof(AppPageTitle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Score Page.
        /// </summary>
        public static string BaseScorePage {
            get {
                return ResourceManager.GetString("BaseScorePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Score Page Update.
        /// </summary>
        public static string BaseScorePageUpdate {
            get {
                return ResourceManager.GetString("BaseScorePageUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification Professor.
        /// </summary>
        public static string ClassificationProfessor {
            get {
                return ResourceManager.GetString("ClassificationProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification Professor Update.
        /// </summary>
        public static string ClassificationProfessorUpdate {
            get {
                return ResourceManager.GetString("ClassificationProfessorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Management.
        /// </summary>
        public static string EducationManagement {
            get {
                return ResourceManager.GetString("EducationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Page.
        /// </summary>
        public static string IndexPage {
            get {
                return ResourceManager.GetString("IndexPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Type.
        /// </summary>
        public static string LearningType {
            get {
                return ResourceManager.GetString("LearningType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Type Update.
        /// </summary>
        public static string LearningTypeUpdate {
            get {
                return ResourceManager.GetString("LearningTypeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Page.
        /// </summary>
        public static string LoginPage {
            get {
                return ResourceManager.GetString("LoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Page.
        /// </summary>
        public static string RegisterPage {
            get {
                return ResourceManager.GetString("RegisterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request To Teach Page.
        /// </summary>
        public static string RequestToTeachPage {
            get {
                return ResourceManager.GetString("RequestToTeachPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Panel.
        /// </summary>
        public static string UserPanel {
            get {
                return ResourceManager.GetString("UserPanel", resourceCulture);
            }
        }
    }
}
