//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Law.
        /// </summary>
        public static string AcceptLaw {
            get {
                return ResourceManager.GetString("AcceptLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha Expired Or Wrong.
        /// </summary>
        public static string CaptchaExpiredOrWrong {
            get {
                return ResourceManager.GetString("CaptchaExpiredOrWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Exists.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Type.
        /// </summary>
        public static string EmailType {
            get {
                return ResourceManager.GetString("EmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Not Find.
        /// </summary>
        public static string EntityNotFind {
            get {
                return ResourceManager.GetString("EntityNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred On Upload File.
        /// </summary>
        public static string ErrorOccuredOnUploadFile {
            get {
                return ResourceManager.GetString("ErrorOccuredOnUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Send Messages.
        /// </summary>
        public static string FailedSendMessages {
            get {
                return ResourceManager.GetString("FailedSendMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its Self Father.
        /// </summary>
        public static string ItsSelfFather {
            get {
                return ResourceManager.GetString("ItsSelfFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Len.
        /// </summary>
        public static string MaxLen {
            get {
                return ResourceManager.GetString("MaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Len With Name.
        /// </summary>
        public static string MaxLenWithName {
            get {
                return ResourceManager.GetString("MaxLenWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Len.
        /// </summary>
        public static string MinLen {
            get {
                return ResourceManager.GetString("MinLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Len With Name.
        /// </summary>
        public static string MinLenWithName {
            get {
                return ResourceManager.GetString("MinLenWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not A Class.
        /// </summary>
        public static string NotAClass {
            get {
                return ResourceManager.GetString("NotAClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allow Modify.
        /// </summary>
        public static string NotAllowModify {
            get {
                return ResourceManager.GetString("NotAllowModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Find.
        /// </summary>
        public static string NotFind {
            get {
                return ResourceManager.GetString("NotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Find Any Record.
        /// </summary>
        public static string NotFindAnyRecord {
            get {
                return ResourceManager.GetString("NotFindAnyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Find Role.
        /// </summary>
        public static string NotFindRole {
            get {
                return ResourceManager.GetString("NotFindRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Find With Field.
        /// </summary>
        public static string NotFindWithField {
            get {
                return ResourceManager.GetString("NotFindWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Same Password.
        /// </summary>
        public static string NotSamePassword {
            get {
                return ResourceManager.GetString("NotSamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Valid Field.
        /// </summary>
        public static string NotValidField {
            get {
                return ResourceManager.GetString("NotValidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Valid File.
        /// </summary>
        public static string NotValidFile {
            get {
                return ResourceManager.GetString("NotValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Valid Model.
        /// </summary>
        public static string NotValidModel {
            get {
                return ResourceManager.GetString("NotValidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Numbers Above Zero.
        /// </summary>
        public static string OnlyNumbersAboveZero {
            get {
                return ResourceManager.GetString("OnlyNumbersAboveZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Selected File Allowed With Param.
        /// </summary>
        public static string OnlySeletedFileAllowedWithParam {
            get {
                return ResourceManager.GetString("OnlySeletedFileAllowedWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Of Min Max.
        /// </summary>
        public static string OutofMinMax {
            get {
                return ResourceManager.GetString("OutofMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Of Min Max Number.
        /// </summary>
        public static string OutofMinMaxNumber {
            get {
                return ResourceManager.GetString("OutofMinMaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Of Min Max Text.
        /// </summary>
        public static string OutofMinMaxText {
            get {
                return ResourceManager.GetString("OutofMinMaxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Occurred.
        /// </summary>
        public static string ProblemOccurred {
            get {
                return ResourceManager.GetString("ProblemOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required With Field Name.
        /// </summary>
        public static string RequiredWithFieldName {
            get {
                return ResourceManager.GetString("RequiredWithFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Unvalid.
        /// </summary>
        public static string RoleUnvalid {
            get {
                return ResourceManager.GetString("RoleUnvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnValid.
        /// </summary>
        public static string UnValid {
            get {
                return ResourceManager.GetString("UnValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnValid Id.
        /// </summary>
        public static string UnValidId {
            get {
                return ResourceManager.GetString("UnValidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un Valid Password.
        /// </summary>
        public static string UnValidPassword {
            get {
                return ResourceManager.GetString("UnValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Is Duplicated.
        /// </summary>
        public static string UsernameIsDuplicated {
            get {
                return ResourceManager.GetString("UsernameIsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Find.
        /// </summary>
        public static string UserNotFind {
            get {
                return ResourceManager.GetString("UserNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Code Or Expire Msg.
        /// </summary>
        public static string WrongCodeOrExpireMsg {
            get {
                return ResourceManager.GetString("WrongCodeOrExpireMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Email Or Password.
        /// </summary>
        public static string WrongEmailOrPassword {
            get {
                return ResourceManager.GetString("WrongEmailOrPassword", resourceCulture);
            }
        }
    }
}
