//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MeshkatMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeshkatMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Resources.MeshkatMessage", typeof(MeshkatMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Meshkat System.
        /// </summary>
        public static string DashboardMeshkatSystem {
            get {
                return ResourceManager.GetString("DashboardMeshkatSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login In Meshkat System.
        /// </summary>
        public static string LoginInMeshkatSystem {
            get {
                return ResourceManager.GetString("LoginInMeshkatSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mashkat System Management Dashboard.
        /// </summary>
        public static string MashkatSystemManagementDashboard {
            get {
                return ResourceManager.GetString("MashkatSystemManagementDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meshkat.
        /// </summary>
        public static string Meshkat {
            get {
                return ResourceManager.GetString("Meshkat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islamic Azad University Development and Technology.
        /// </summary>
        public static string Meshkat_Author_Name {
            get {
                return ResourceManager.GetString("Meshkat Author Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meshkat.
        /// </summary>
        public static string MeshkatSystem {
            get {
                return ResourceManager.GetString("MeshkatSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otp Message.
        /// </summary>
        public static string OtpMessage {
            get {
                return ResourceManager.GetString("OtpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register In System Meshkat.
        /// </summary>
        public static string RegisterInSystemMeshkat {
            get {
                return ResourceManager.GetString("RegisterInSystemMeshkat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which course are you looking to learn?.
        /// </summary>
        public static string SearchPlaceHolderContent {
            get {
                return ResourceManager.GetString("SearchPlaceHolderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Login To Meshkat.
        /// </summary>
        public static string SuccessfullyLoginToMeshkat {
            get {
                return ResourceManager.GetString("SuccessfullyLoginToMeshkat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching In System Meshkat.
        /// </summary>
        public static string TeachingInSystemMeshkat {
            get {
                return ResourceManager.GetString("TeachingInSystemMeshkat", resourceCulture);
            }
        }
    }
}
