//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 404 .
        /// </summary>
        public static string _404ErrorNotFoundMessages {
            get {
                return ResourceManager.GetString("_404ErrorNotFoundMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Status.
        /// </summary>
        public static string AcceptedStatus {
            get {
                return ResourceManager.GetString("AcceptedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acc Number Status.
        /// </summary>
        public static string AccNumberStatus {
            get {
                return ResourceManager.GetString("AccNumberStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settlement.
        /// </summary>
        public static string AccountSettlement {
            get {
                return ResourceManager.GetString("AccountSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active User.
        /// </summary>
        public static string ActiveUser {
            get {
                return ResourceManager.GetString("ActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Users.
        /// </summary>
        public static string ActiveUsers {
            get {
                return ResourceManager.GetString("ActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Profile.
        /// </summary>
        public static string AdditionalProfile {
            get {
                return ResourceManager.GetString("AdditionalProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Record.
        /// </summary>
        public static string AddNewRecord {
            get {
                return ResourceManager.GetString("AddNewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Score.
        /// </summary>
        public static string AddNewScore {
            get {
                return ResourceManager.GetString("AddNewScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Courses.
        /// </summary>
        public static string AllCourses {
            get {
                return ResourceManager.GetString("AllCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Image Format.
        /// </summary>
        public static string AllowedImageFormat {
            get {
                return ResourceManager.GetString("AllowedImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Toman.
        /// </summary>
        public static string AmountToman {
            get {
                return ResourceManager.GetString("AmountToman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Item Count.
        /// </summary>
        public static string AssessmentItemCount {
            get {
                return ResourceManager.GetString("AssessmentItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Shaba Saderat.
        /// </summary>
        public static string BankShabaSaderat {
            get {
                return ResourceManager.GetString("BankShabaSaderat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Scores.
        /// </summary>
        public static string BaseScores {
            get {
                return ResourceManager.GetString("BaseScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Sciences.
        /// </summary>
        public static string BasicSciences {
            get {
                return ResourceManager.GetString("BasicSciences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Selling.
        /// </summary>
        public static string Best_Selling {
            get {
                return ResourceManager.GetString("Best Selling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Day.
        /// </summary>
        public static string BirthDay {
            get {
                return ResourceManager.GetString("BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Management.
        /// </summary>
        public static string BusinessManagement {
            get {
                return ResourceManager.GetString("BusinessManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity Has Been Reached.
        /// </summary>
        public static string CapacityHasBeenReached {
            get {
                return ResourceManager.GetString("CapacityHasBeenReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Organization of Islamic Azad University.
        /// </summary>
        public static string Central_Organization_of_Islamic_Azad_University {
            get {
                return ResourceManager.GetString("Central Organization of Islamic Azad University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        public static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Type Title.
        /// </summary>
        public static string certificateTypeTitle {
            get {
                return ResourceManager.GetString("certificateTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password As Soon As Possible.
        /// </summary>
        public static string ChangeItAsSoonAsPossible {
            get {
                return ResourceManager.GetString("ChangeItAsSoonAsPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheapest.
        /// </summary>
        public static string Cheapest {
            get {
                return ResourceManager.GetString("Cheapest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Below Link To Enter Site.
        /// </summary>
        public static string ClickBellowLinkToEnterSite {
            get {
                return ResourceManager.GetString("ClickBellowLinkToEnterSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cnt Course Assessments.
        /// </summary>
        public static string CntCourseAssessments {
            get {
                return ResourceManager.GetString("CntCourseAssessments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cnt Course Contents.
        /// </summary>
        public static string CntCourseContents {
            get {
                return ResourceManager.GetString("CntCourseContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combinatorial Course.
        /// </summary>
        public static string CombinatorialCourse {
            get {
                return ResourceManager.GetString("CombinatorialCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string CommingSoon {
            get {
                return ResourceManager.GetString("CommingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conducting online exams.
        /// </summary>
        public static string Conducting_online_exams {
            get {
                return ResourceManager.GetString("Conducting online exams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course category.
        /// </summary>
        public static string Course_category {
            get {
                return ResourceManager.GetString("Course category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Categories.
        /// </summary>
        public static string CourseCategories {
            get {
                return ResourceManager.GetString("CourseCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Course Is Deleted.
        /// </summary>
        public static string CourseDeleted {
            get {
                return ResourceManager.GetString("CourseDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course End Date.
        /// </summary>
        public static string CourseEndDate {
            get {
                return ResourceManager.GetString("CourseEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TheCourseHasEnded.
        /// </summary>
        public static string CourseEnded {
            get {
                return ResourceManager.GetString("CourseEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Group.
        /// </summary>
        public static string CourseGroup {
            get {
                return ResourceManager.GetString("CourseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Id.
        /// </summary>
        public static string CourseId {
            get {
                return ResourceManager.GetString("CourseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Info.
        /// </summary>
        public static string CourseInfo {
            get {
                return ResourceManager.GetString("CourseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Course is not active.
        /// </summary>
        public static string CourseIsNotActive {
            get {
                return ResourceManager.GetString("CourseIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        public static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Organizer.
        /// </summary>
        public static string CourseOrganizer {
            get {
                return ResourceManager.GetString("CourseOrganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Register Count.
        /// </summary>
        public static string CourseRegisterCount {
            get {
                return ResourceManager.GetString("CourseRegisterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Start Date.
        /// </summary>
        public static string CourseStartDate {
            get {
                return ResourceManager.GetString("CourseStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses Title.
        /// </summary>
        public static string CoursesTitle {
            get {
                return ResourceManager.GetString("CoursesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Time.
        /// </summary>
        public static string CourseTime {
            get {
                return ResourceManager.GetString("CourseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Type.
        /// </summary>
        public static string CourseType {
            get {
                return ResourceManager.GetString("CourseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course With Discount.
        /// </summary>
        public static string CourseWithDiscount {
            get {
                return ResourceManager.GetString("CourseWithDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditor.
        /// </summary>
        public static string Creditor {
            get {
                return ResourceManager.GetString("Creditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor.
        /// </summary>
        public static string Debtor {
            get {
                return ResourceManager.GetString("Debtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Payed.
        /// </summary>
        public static string DetailPayed {
            get {
                return ResourceManager.GetString("DetailPayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determining Educational Points.
        /// </summary>
        public static string DeterminingEducationalPoints {
            get {
                return ResourceManager.GetString("DeterminingEducationalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islamic Azad University Development and Technology .
        /// </summary>
        public static string DevelopementOrgin {
            get {
                return ResourceManager.GetString("DevelopementOrgin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islamic Azad University Development and Technology.
        /// </summary>
        public static string DevelopementOrgins {
            get {
                return ResourceManager.GetString("DevelopementOrgins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounted.
        /// </summary>
        public static string Discounted {
            get {
                return ResourceManager.GetString("Discounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Precent.
        /// </summary>
        public static string DiscountPrecent {
            get {
                return ResourceManager.GetString("DiscountPrecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Roles Count.
        /// </summary>
        public static string DomainRolesCount {
            get {
                return ResourceManager.GetString("DomainRolesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Title.
        /// </summary>
        public static string DomainTitle {
            get {
                return ResourceManager.GetString("DomainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Experience.
        /// </summary>
        public static string EducationalExperience {
            get {
                return ResourceManager.GetString("EducationalExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Main Page.
        /// </summary>
        public static string EnterMainPage {
            get {
                return ResourceManager.GetString("EnterMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Online Class.
        /// </summary>
        public static string EnterOnlineClass {
            get {
                return ResourceManager.GetString("EnterOnlineClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter The Number In The Picture In The Box Below.
        /// </summary>
        public static string EnterTheNumberInThePicture_InTheBoxBelow {
            get {
                return ResourceManager.GetString("EnterTheNumberInThePicture InTheBoxBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Password Here.
        /// </summary>
        public static string EnterYouPasswordHere {
            get {
                return ResourceManager.GetString("EnterYouPasswordHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Username Here.
        /// </summary>
        public static string EnterYourUsernameHere {
            get {
                return ResourceManager.GetString("EnterYourUsernameHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Date.
        /// </summary>
        public static string ExamDate {
            get {
                return ResourceManager.GetString("ExamDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Date End.
        /// </summary>
        public static string ExamDateEnd {
            get {
                return ResourceManager.GetString("ExamDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exams.
        /// </summary>
        public static string Exams {
            get {
                return ResourceManager.GetString("Exams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Time Elapsed.
        /// </summary>
        public static string ExamTimeElapsed {
            get {
                return ResourceManager.GetString("ExamTimeElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Title.
        /// </summary>
        public static string ExamTitle {
            get {
                return ResourceManager.GetString("ExamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Type.
        /// </summary>
        public static string ExamType {
            get {
                return ResourceManager.GetString("ExamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail Check User Password.
        /// </summary>
        public static string FailCheckUserPassword {
            get {
                return ResourceManager.GetString("FailCheckUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance and Investment.
        /// </summary>
        public static string FinanceAndInvestment {
            get {
                return ResourceManager.GetString("FinanceAndInvestment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial.
        /// </summary>
        public static string Financial {
            get {
                return ResourceManager.GetString("Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Account Information.
        /// </summary>
        public static string FinancialAccountInformation {
            get {
                return ResourceManager.GetString("FinancialAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Management.
        /// </summary>
        public static string FinancialManagement {
            get {
                return ResourceManager.GetString("FinancialManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For What.
        /// </summary>
        public static string ForWhat {
            get {
                return ResourceManager.GetString("ForWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions.
        /// </summary>
        public static string Frequently_Asked_Questions {
            get {
                return ResourceManager.GetString("Frequently Asked Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Further Details.
        /// </summary>
        public static string FurtherDetails {
            get {
                return ResourceManager.GetString("FurtherDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holding courses and meetings.
        /// </summary>
        public static string HoldingCoursesAndMeetings {
            get {
                return ResourceManager.GetString("HoldingCoursesAndMeetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holding Date Start.
        /// </summary>
        public static string HoldingDateStart {
            get {
                return ResourceManager.GetString("HoldingDateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holding offline and online in-person courses.
        /// </summary>
        public static string HoldingOfflineAndOnlineIn_personCourses {
            get {
                return ResourceManager.GetString("HoldingOfflineAndOnlineIn-personCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor name.
        /// </summary>
        public static string Instructor_name {
            get {
                return ResourceManager.GetString("Instructor name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Accepted Certificate.
        /// </summary>
        public static string IsAcceptedCertificate {
            get {
                return ResourceManager.GetString("IsAcceptedCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Public.
        /// </summary>
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judge Portable.
        /// </summary>
        public static string JudgePortable {
            get {
                return ResourceManager.GetString("JudgePortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judge Teaching Requests.
        /// </summary>
        public static string JudgeTeachingRequests {
            get {
                return ResourceManager.GetString("JudgeTeachingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Course.
        /// </summary>
        public static string LatestCourse {
            get {
                return ResourceManager.GetString("LatestCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Free Course.
        /// </summary>
        public static string LatestFreeCourse {
            get {
                return ResourceManager.GetString("LatestFreeCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Type.
        /// </summary>
        public static string LearningType {
            get {
                return ResourceManager.GetString("LearningType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lms Dashboard.
        /// </summary>
        public static string LmsDashboard {
            get {
                return ResourceManager.GetString("LmsDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Waiting.
        /// </summary>
        public static string Loading_Watting {
            get {
                return ResourceManager.GetString("Loading_Watting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Meshkat User System.
        /// </summary>
        public static string Login_to_Meshkat_User_System {
            get {
                return ResourceManager.GetString("Login to Meshkat User System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In Sign Up.
        /// </summary>
        public static string LogInSignUp {
            get {
                return ResourceManager.GetString("LogInSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login To Online Class.
        /// </summary>
        public static string LoginToOnlineClass {
            get {
                return ResourceManager.GetString("LoginToOnlineClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login To System.
        /// </summary>
        public static string LoginToSystem {
            get {
                return ResourceManager.GetString("LoginToSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        public static string Main_Page {
            get {
                return ResourceManager.GetString("Main Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Size Pic Profile.
        /// </summary>
        public static string MaxSizePicProfile {
            get {
                return ResourceManager.GetString("MaxSizePicProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Sciences.
        /// </summary>
        public static string MedicalSciences {
            get {
                return ResourceManager.GetString("MedicalSciences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meshkat System Links.
        /// </summary>
        public static string Meshkat_System_Links {
            get {
                return ResourceManager.GetString("Meshkat System Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meshkat Teachers Area.
        /// </summary>
        public static string Meshkat_Teachers_Area {
            get {
                return ResourceManager.GetString("Meshkat Teachers Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meshkat User Area.
        /// </summary>
        public static string Meshkat_User_Area {
            get {
                return ResourceManager.GetString("Meshkat User Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Meshkat system (Management of the National Empowerment Education Network) was created with the mission of organizing skill-building and empowerment courses across the Islamic Azad University..
        /// </summary>
        public static string MeshkatDescriptions {
            get {
                return ResourceManager.GetString("MeshkatDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging And Correspondence Management.
        /// </summary>
        public static string MessagingAndCorrespondenceManagement {
            get {
                return ResourceManager.GetString("MessagingAndCorrespondenceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method of holding.
        /// </summary>
        public static string Method_of_holding {
            get {
                return ResourceManager.GetString("Method of holding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Login Registration.
        /// </summary>
        public static string MobileLogin_registration {
            get {
                return ResourceManager.GetString("MobileLogin_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Expensive.
        /// </summary>
        public static string Most_Expensive {
            get {
                return ResourceManager.GetString("Most Expensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Popular.
        /// </summary>
        public static string Most_Popular {
            get {
                return ResourceManager.GetString("Most Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Certificate.
        /// </summary>
        public static string MyCertificate {
            get {
                return ResourceManager.GetString("MyCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Courses.
        /// </summary>
        public static string MyCourses {
            get {
                return ResourceManager.GetString("MyCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Exams.
        /// </summary>
        public static string MyExams {
            get {
                return ResourceManager.GetString("MyExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Payment.
        /// </summary>
        public static string MyPayment {
            get {
                return ResourceManager.GetString("MyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Card.
        /// </summary>
        public static string NactionalCard {
            get {
                return ResourceManager.GetString("NactionalCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name And Family.
        /// </summary>
        public static string NameAndFamily {
            get {
                return ResourceManager.GetString("NameAndFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Of Account Holder.
        /// </summary>
        public static string NameOfAccountHolder {
            get {
                return ResourceManager.GetString("NameOfAccountHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Code.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Teaching Request.
        /// </summary>
        public static string NewTeachingRequest {
            get {
                return ResourceManager.GetString("NewTeachingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not free.
        /// </summary>
        public static string Not_free {
            get {
                return ResourceManager.GetString("Not free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allow Modify.
        /// </summary>
        public static string NotAllowModify {
            get {
                return ResourceManager.GetString("NotAllowModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Registered Any Acc Number.
        /// </summary>
        public static string NotRegisteredAnyAccNumber {
            get {
                return ResourceManager.GetString("NotRegisteredAnyAccNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Selected File.
        /// </summary>
        public static string NotSelectedFile {
            get {
                return ResourceManager.GetString("NotSelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office of the Supreme Leader Information Base.
        /// </summary>
        public static string Office_of_the_Supreme_Leader_Information_Base {
            get {
                return ResourceManager.GetString("Office of the Supreme Leader Information Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Courses.
        /// </summary>
        public static string OfflineCourses {
            get {
                return ResourceManager.GetString("OfflineCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest.
        /// </summary>
        public static string Oldest {
            get {
                return ResourceManager.GetString("Oldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Courses.
        /// </summary>
        public static string Online_Courses {
            get {
                return ResourceManager.GetString("Online Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Payment Id.
        /// </summary>
        public static string OnlinePaymentId {
            get {
                return ResourceManager.GetString("OnlinePaymentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order By.
        /// </summary>
        public static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational Training (Islamic Azad University).
        /// </summary>
        public static string Organizational_Training__Islamic_Azad_University_ {
            get {
                return ResourceManager.GetString("Organizational Training (Islamic Azad University)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizing unit.
        /// </summary>
        public static string Organizing_unit {
            get {
                return ResourceManager.GetString("Organizing unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otp Message.
        /// </summary>
        public static string OtpMessage {
            get {
                return ResourceManager.GetString("OtpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page is not founded.
        /// </summary>
        public static string PageNotFoundMessage {
            get {
                return ResourceManager.GetString("PageNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass Requirement.
        /// </summary>
        public static string PassRequirement {
            get {
                return ResourceManager.GetString("PassRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Len Requirement.
        /// </summary>
        public static string PassWordLenRequirement {
            get {
                return ResourceManager.GetString("PassWordLenRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payed Amount.
        /// </summary>
        public static string PayedAmount {
            get {
                return ResourceManager.GetString("PayedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payed Amount Toman.
        /// </summary>
        public static string PayedAmountToman {
            get {
                return ResourceManager.GetString("PayedAmountToman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payed Result.
        /// </summary>
        public static string PayedResult {
            get {
                return ResourceManager.GetString("PayedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payed State.
        /// </summary>
        public static string PayedState {
            get {
                return ResourceManager.GetString("PayedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payed Time.
        /// </summary>
        public static string PayedTime {
            get {
                return ResourceManager.GetString("PayedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer.
        /// </summary>
        public static string Payer {
            get {
                return ResourceManager.GetString("Payer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Reports.
        /// </summary>
        public static string PaymentReports {
            get {
                return ResourceManager.GetString("PaymentReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment To.
        /// </summary>
        public static string PaymentTo {
            get {
                return ResourceManager.GetString("PaymentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Final.
        /// </summary>
        public static string Price_Final {
            get {
                return ResourceManager.GetString("Price_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Final Toman.
        /// </summary>
        public static string Price_FinalToman {
            get {
                return ResourceManager.GetString("Price_FinalToman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Old.
        /// </summary>
        public static string Price_Old {
            get {
                return ResourceManager.GetString("Price_Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Old Toman.
        /// </summary>
        public static string Price_OldToman {
            get {
                return ResourceManager.GetString("Price_OldToman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Profile.
        /// </summary>
        public static string ProfessionalProfile {
            get {
                return ResourceManager.GetString("ProfessionalProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professors Leveling Criteria.
        /// </summary>
        public static string ProfessorsLevelingCriteria {
            get {
                return ResourceManager.GetString("ProfessorsLevelingCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programing.
        /// </summary>
        public static string Programing {
            get {
                return ResourceManager.GetString("Programing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProvideCredibleCertificate.
        /// </summary>
        public static string ProvideCredibleCertificate {
            get {
                return ResourceManager.GetString("ProvideCredibleCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        public static string Quick_Links {
            get {
                return ResourceManager.GetString("Quick Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Link.
        /// </summary>
        public static string QuikLink {
            get {
                return ResourceManager.GetString("QuikLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        public static string QuikLinks {
            get {
                return ResourceManager.GetString("QuikLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee Message.
        /// </summary>
        public static string RefereeMessage {
            get {
                return ResourceManager.GetString("RefereeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register End Date.
        /// </summary>
        public static string RegisterEndDate {
            get {
                return ResourceManager.GetString("RegisterEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Information.
        /// </summary>
        public static string RegisterInformation {
            get {
                return ResourceManager.GetString("RegisterInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register In System.
        /// </summary>
        public static string RegisterInSystem {
            get {
                return ResourceManager.GetString("RegisterInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register On Course.
        /// </summary>
        public static string RegisterOnCourse {
            get {
                return ResourceManager.GetString("RegisterOnCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Start Date.
        /// </summary>
        public static string RegisterStartDate {
            get {
                return ResourceManager.GetString("RegisterStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration has ended.
        /// </summary>
        public static string RegistrationEnded {
            get {
                return ResourceManager.GetString("RegistrationEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Capacity.
        /// </summary>
        public static string RemainingCapacity {
            get {
                return ResourceManager.GetString("RemainingCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Capacity.
        /// </summary>
        public static string RemaningCapacity {
            get {
                return ResourceManager.GetString("RemaningCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Teaching List.
        /// </summary>
        public static string RequestTeachingList {
            get {
                return ResourceManager.GetString("RequestTeachingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To Course.
        /// </summary>
        public static string ReturnToCourse {
            get {
                return ResourceManager.GetString("ReturnToCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To First State.
        /// </summary>
        public static string ReturnToFirstState {
            get {
                return ResourceManager.GetString("ReturnToFirstState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Number.
        /// </summary>
        public static string RowNumber {
            get {
                return ResourceManager.GetString("RowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Change.
        /// </summary>
        public static string SaveChange {
            get {
                return ResourceManager.GetString("SaveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Or Update Acc Info.
        /// </summary>
        public static string SaveOrUpdateAccInfo {
            get {
                return ResourceManager.GetString("SaveOrUpdateAccInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Photo.
        /// </summary>
        public static string SavePhoto {
            get {
                return ResourceManager.GetString("SavePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific Leveling.
        /// </summary>
        public static string Scientificleveling {
            get {
                return ResourceManager.GetString("Scientificleveling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Based On.
        /// </summary>
        public static string SearchBasedOn {
            get {
                return ResourceManager.GetString("SearchBasedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State.
        /// </summary>
        public static string SelectState {
            get {
                return ResourceManager.GetString("SelectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement Request.
        /// </summary>
        public static string SettlementRequest {
            get {
                return ResourceManager.GetString("SettlementRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement Requests.
        /// </summary>
        public static string SettlementRequests {
            get {
                return ResourceManager.GetString("SettlementRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shamsi Date.
        /// </summary>
        public static string ShamsiDate {
            get {
                return ResourceManager.GetString("ShamsiDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing Payed.
        /// </summary>
        public static string SharingPayed {
            get {
                return ResourceManager.GetString("SharingPayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show inactive courses.
        /// </summary>
        public static string Show_inactive_courses {
            get {
                return ResourceManager.GetString("Show inactive courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowMore.
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sodor Date.
        /// </summary>
        public static string SodorDate {
            get {
                return ResourceManager.GetString("SodorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialized courses.
        /// </summary>
        public static string SpecializedCourses {
            get {
                return ResourceManager.GetString("SpecializedCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Count.
        /// </summary>
        public static string StudentCount {
            get {
                return ResourceManager.GetString("StudentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Payment Was Successfully.
        /// </summary>
        public static string SuccessedPayment {
            get {
                return ResourceManager.GetString("SuccessedPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Logout.
        /// </summary>
        public static string SuccessFullyLogout {
            get {
                return ResourceManager.GetString("SuccessFullyLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Register.
        /// </summary>
        public static string SuccessfullyRegister {
            get {
                return ResourceManager.GetString("SuccessfullyRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Login.
        /// </summary>
        public static string SuccessLogin {
            get {
                return ResourceManager.GetString("SuccessLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Operation.
        /// </summary>
        public static string SuccessOperation {
            get {
                return ResourceManager.GetString("SuccessOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Update Info Operation.
        /// </summary>
        public static string SuccessUpdateInfoOperation {
            get {
                return ResourceManager.GetString("SuccessUpdateInfoOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Score.
        /// </summary>
        public static string SumScore {
            get {
                return ResourceManager.GetString("SumScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admin Portal.
        /// </summary>
        public static string SuperAdminPortal {
            get {
                return ResourceManager.GetString("SuperAdminPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Management.
        /// </summary>
        public static string SystemManagement {
            get {
                return ResourceManager.GetString("SystemManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Request.
        /// </summary>
        public static string Teaching_Request {
            get {
                return ResourceManager.GetString("Teaching Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Requests.
        /// </summary>
        public static string Teaching_Requests {
            get {
                return ResourceManager.GetString("Teaching Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Portable.
        /// </summary>
        public static string TeachingPortable {
            get {
                return ResourceManager.GetString("TeachingPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Request.
        /// </summary>
        public static string TeachingRequest {
            get {
                return ResourceManager.GetString("TeachingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Requests.
        /// </summary>
        public static string TeachingRequests {
            get {
                return ResourceManager.GetString("TeachingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Requests Judge.
        /// </summary>
        public static string TeachingRequests_Judge {
            get {
                return ResourceManager.GetString("TeachingRequests_Judge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical and Engineering.
        /// </summary>
        public static string TechnicalAndEngineering {
            get {
                return ResourceManager.GetString("TechnicalAndEngineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Latest.
        /// </summary>
        public static string TheLatest {
            get {
                return ResourceManager.GetString("TheLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toman.
        /// </summary>
        public static string Toman {
            get {
                return ResourceManager.GetString("Toman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Code.
        /// </summary>
        public static string TrackingCode {
            get {
                return ResourceManager.GetString("TrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking ID.
        /// </summary>
        public static string TrackingID {
            get {
                return ResourceManager.GetString("TrackingID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training hours.
        /// </summary>
        public static string Traininghours {
            get {
                return ResourceManager.GetString("Traininghours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Specifications.
        /// </summary>
        public static string TrainingSpecifications {
            get {
                return ResourceManager.GetString("TrainingSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Course.
        /// </summary>
        public static string TypeCourse {
            get {
                return ResourceManager.GetString("TypeCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un Accepted Status.
        /// </summary>
        public static string UnAcceptedStatus {
            get {
                return ResourceManager.GetString("UnAcceptedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnDefined.
        /// </summary>
        public static string UnDefined {
            get {
                return ResourceManager.GetString("UnDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Degree.
        /// </summary>
        public static string UploadDeggree {
            get {
                return ResourceManager.GetString("UploadDeggree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Edit.
        /// </summary>
        public static string UploadEdit {
            get {
                return ResourceManager.GetString("UploadEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload National Card.
        /// </summary>
        public static string UploadNationalCard {
            get {
                return ResourceManager.GetString("UploadNationalCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload New Photo.
        /// </summary>
        public static string UploadNewPhoto {
            get {
                return ResourceManager.GetString("UploadNewPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Resume.
        /// </summary>
        public static string UploadResume {
            get {
                return ResourceManager.GetString("UploadResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string Useful_Links {
            get {
                return ResourceManager.GetString("Useful Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Permission Management.
        /// </summary>
        public static string UserPermissionManagement {
            get {
                return ResourceManager.GetString("UserPermissionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string UserPersonalInfoManagement {
            get {
                return ResourceManager.GetString("UserPersonalInfoManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile Detail.
        /// </summary>
        public static string UserProfileDetail {
            get {
                return ResourceManager.GetString("UserProfileDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Format Is.
        /// </summary>
        public static string ValidFormatis {
            get {
                return ResourceManager.GetString("ValidFormatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Formats Is.
        /// </summary>
        public static string ValidFormatsis {
            get {
                return ResourceManager.GetString("ValidFormatsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbal Course.
        /// </summary>
        public static string Verbal_Course {
            get {
                return ResourceManager.GetString("Verbal Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        public static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Acc Number.
        /// </summary>
        public static string YouAccNumber {
            get {
                return ResourceManager.GetString("YouAccNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Registered On Course.
        /// </summary>
        public static string YourRegisteredOnCourse {
            get {
                return ResourceManager.GetString("YourRegisteredOnCourse", resourceCulture);
            }
        }
    }
}
