//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RoleName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoleName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Resources.RoleName", typeof(RoleName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azad University Employee.
        /// </summary>
        public static string AzadUniversityEmployee {
            get {
                return ResourceManager.GetString("AzadUniversityEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azad University Faculty.
        /// </summary>
        public static string AzadUniversityFaculty {
            get {
                return ResourceManager.GetString("AzadUniversityFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azad University Student.
        /// </summary>
        public static string AzadUniversityStudent {
            get {
                return ResourceManager.GetString("AzadUniversityStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Expert.
        /// </summary>
        public static string EducationalExpert {
            get {
                return ResourceManager.GetString("EducationalExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Connector.
        /// </summary>
        public static string EducationConnector {
            get {
                return ResourceManager.GetString("EducationConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive Secretary.
        /// </summary>
        public static string ExecutiveSecretary {
            get {
                return ResourceManager.GetString("ExecutiveSecretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Connector.
        /// </summary>
        public static string FinancialConnector {
            get {
                return ResourceManager.GetString("FinancialConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant.
        /// </summary>
        public static string Participant {
            get {
                return ResourceManager.GetString("Participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee.
        /// </summary>
        public static string Referee {
            get {
                return ResourceManager.GetString("Referee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Connector.
        /// </summary>
        public static string ResearchConnector {
            get {
                return ResourceManager.GetString("ResearchConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Researcher.
        /// </summary>
        public static string Researcher {
            get {
                return ResourceManager.GetString("Researcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScientificSecretary.
        /// </summary>
        public static string ScientificSecretary {
            get {
                return ResourceManager.GetString("ScientificSecretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secretary Of The Arbitration Committee.
        /// </summary>
        public static string SecretaryOfTheArbitrationCommittee {
            get {
                return ResourceManager.GetString("SecretaryOfTheArbitrationCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admin.
        /// </summary>
        public static string SuperAdmin {
            get {
                return ResourceManager.GetString("SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admin Financial.
        /// </summary>
        public static string SuperAdminFinancial {
            get {
                return ResourceManager.GetString("SuperAdminFinancial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University Student.
        /// </summary>
        public static string UniversityStudent {
            get {
                return ResourceManager.GetString("UniversityStudent", resourceCulture);
            }
        }
    }
}
